read data set

In [16]:
import pandas as pd
data=pd.read_csv("C:\datasets\synthetic_retail_100k_realistic.csv")

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Mega Store\AppData\Local\Temp\ipykernel_7764\1045206704.py:2: SyntaxWarning: invalid escape sequence '\d'
  data=pd.read_csv("C:\datasets\synthetic_retail_100k_realistic.csv")

,customer_id,store_name,transaction_date,aisle,product_name,quantity,unit_price,total_amount,discount_amount,final_amount,loyalty_points
0,2824,QuickStop Market,31/01/2023,Produce,Bananas,2,10.13,20.26,2.33,17.93,207
1,3286,QuickStop Market,22/12/2020,Snacks,Chocolate,1,1.62,1.62,0.04,1.58,20
2,1520,QuickStop Market,18/01/2021,Produce,Bananas,3,7.52,22.56,0.51,22.05,304
3,9279,QuickStop Market,25/03/2022,Snacks,Chocolate,5,1.92,9.60,0.42,9.18,83
4,4611,UrbanGrocers,13/02/2023,Bakery,Bread,2,4.34,8.68,0.66,8.02,78

In [26]:
data= data.drop(columns=['customer_id'])

In [38]:
data.head()

,store_name,transaction_date,product_name,quantity,unit_price,total_amount,discount_amount,final_amount,loyalty_points
0,QuickStop Market,2020-11-11,Cereal,3,4.06,12.18,1.14,11.04,299
1,QuickStop Market,2025-11-17,Ground Beef,3,8.70,26.10,0.52,25.58,266
2,ValuePlus Market,2022-03-28,Orange Juice,1,4.26,4.26,0.14,4.12,317
3,City Fresh Store,2021-10-28,Apples,2,2.28,4.56,0.66,3.90,151
4,QuickStop Market,2025-05-10,Eggs,3,3.39,10.17,0.92,9.25,221

In [17]:
data['transaction_date'] = pd.to_datetime(data['transaction_date'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   customer_id       100000 non-null  int64
 1   store_name        100000 non-null  object
 2   transaction_date  100000 non-null  datetime64[ns]
 3   aisle             100000 non-null  object
 4   product_name      100000 non-null  object
 5   quantity          100000 non-null  int64
 6   unit_price        100000 non-null  float64
 7   total_amount      100000 non-null  float64
 8   discount_amount   100000 non-null  float64
 9   final_amount      100000 non-null  float64
 10  loyalty_points    100000 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 8.4+ MB

C:\Users\Mega Store\AppData\Local\Temp\ipykernel_7764\493093104.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['transaction_date'] = pd.to_datetime(data['transaction_date'])

In [34]:
t_data = data[data['transaction_date'].dt.year<2025]
use_case = data.query('transaction_date.dt.year == 2025')

In [35]:
t_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83347 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   store_name        83347 non-null  object
 1   transaction_date  83347 non-null  datetime64[ns]
 2   aisle             83347 non-null  object
 3   product_name      83347 non-null  object
 4   quantity          83347 non-null  int64
 5   unit_price        83347 non-null  float64
 6   total_amount      83347 non-null  float64
 7   discount_amount   83347 non-null  float64
 8   final_amount      83347 non-null  float64
 9   loyalty_points    83347 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(2), object(3)
memory usage: 7.0+ MB

In [32]:
use_case.to_csv("D:\\depi project\\use_case.csv")

In [36]:
t_data.to_csv("D:\\depi project\\t_data.csv")